### ISSUE TITLE
No support for && syntax 

### ISSUE THREAD

**Issue by AOx0** [linux-china/jetbrains-just-plugin#1]
Everything works fine with pre-recipe syntax. 
Example:

```
rf: pre_recipe
    echo "rf"

pre_recipe:
    echo "pre"
```

But the Just plugin breaks when using ["Running Recipes at the End of a Recipe"](https://github.com/casey/just#running-recipes-at-the-end-of-a-recipe) syntax.
For example:

```
rf: && open_result
    echo "rf"

open_result:
    echo "post"
```

At line 1 where `&&` is used. With the error: 
```
JustToken.COMMENT, JustToken.KEYWORD_ALIAS, JustToken.KEYWORD_EXPORT, JustToken.KEYWORD_SET, JustToken.NEW_LINE, JustToken.RECIPE_NAME, JustToken.SHEBANG or JustToken.VARIABLE expected, got '&'
``` 

Thanks for your work. I really appreciate having a `just` plugin in JetBrains IDEs

**Comment by linux-china** [comment]
Sorry for delay answer because of other work.  It's not hard, and I fixed it. Please upgrade to version 0.2.1 in next 1-2 days.
