### ISSUE TITLE
Feature: Running just recipes as Run configuration

### ISSUE THREAD

**Issue by funkyfuture** [linux-china/jetbrains-just-plugin#10]
there's a review on your plugin that speaks from my heart:

> Does what it says on the tin. The only thing that I wasn't able to find was a way to add the Justfile runs to my run/debug configurations. I'm used to being able to click the arrow in the file and then find it in my debug configs when I use npm. I also didn't see a configuration when I tried manually adding it. This would be a really appreciated feature.

i assume that is expressing what i'm missing: to use just recipes as configuration option in "Run(/Debug) Configurations", similar how the "Makefile Target" can be used there. 

that'd just be a tailored way to invoke recipes than the "Run -> Available Just Recipes".

for me this has three advantages:

- i can keep my beahviour to use the Run Configuration widgets in the main IDE window w/o using an extra menu
- in this context i run just a few selected recipes, not every recipe from the `Justfile`
- and of course, the Run Configurations let's you select from any kind of task / test / whatever runner; so one can invoke these from one widget

**Comment by jihiggins** [comment]
I'd be down to try to add this, if nobody else is working on it / if you're accepting contributions or anything?

(Also, I was setting up a basic version, but it seems like the project fails to build because of missing a bunch of stuff in `org.mvnsearch.plugins.just.lang.psi`, like `JustCodeBlock` ? Not sure if I'm misisng a step or if the files are actually missing)

**Comment by dpeter99** [comment]
I would also love this feature. It would make my multi-language monorepo much easier to manage.

**Comment by linux-china** [comment]
@funkyfuture @dpeter99  Implemented with version 0.6.0, please try later.

**Comment by funkyfuture** [comment]
thanks a lot, that generally works as i imagined.

however, running a recipe from such configured task behaves differently than when selecting with the previously established invokation. it seems that a different execution environment is used.

one effect is mere optical, this is was i was used to:

![grafik](https://github.com/user-attachments/assets/6e3c47dc-4cdf-446c-b358-72e59b230a56)

and this is the new:

![grafik](https://github.com/user-attachments/assets/820f871f-7f50-4701-9c17-ed8a672777c0)

but most importantly, when using PyCharm with a configured Python interpreter environment (that's called *virtual environment* and contains a project's dependencies, and often an "editable" installation of the project package; editable here means that the installed package reflects the current source state on disk), that one isn't active and thus tasks fail because they can't access all necessary context.

**Comment by linux-china** [comment]
@funkyfuture How about `export PATH`?  it works well?

```
#!/usr/bin/env just --justfile
export PATH := join(justfile_directory(), ".env", "bin") + ":" + env_var('PATH')
         
hello:
    python3 --version
```

It's hard to make context correct,  for example direnv.

**Comment by funkyfuture** [comment]
no, that wouldn't address the problem. from a UX perspective it's just irritating why recipes are executed differently when invoked from the menu or a Run configuration.

also it wouldn't help, because not every virtual environment manager places environments in an `.env` folder within a project folder (for some good reasons). in my case PyCharm (as such manager) defaults to look for venvs in my user-folder (`~./virtualenvs`), but there's no constraint where a venv can be located.

i assume that the invokation via menu executes in an environment that PyCharm would also start as terminal/shell for the related widget. that one always 'activates' the configured *Project Interpreter* (which is the python binary in the selected virtual env).

i tried to understand how the new method works, but i'm still too stupid for anything Java-ish. i'm just noticing that *maybe* [this](https://github.com/linux-china/jetbrains-just-plugin/blob/4939d8535b27f1d2cd33c92a0bf0026a845b2fea/src/main/kotlin/org/mvnsearch/plugins/just/lang/run/JustRunAnythingProvider.kt#L69) can be a pointer, as the menu invokation is producing coloured terminal output.

**Comment by linux-china** [comment]
@funkyfuture  I will activate Project Interpreter for justfile execution.  #34
