### ISSUE TITLE
Justfile icon too small

### ISSUE THREAD

**Issue by simonrouse9461** [linux-china/jetbrains-just-plugin#11]
The justfile icon is smaller than the regular icon size. File names are not aligning correctly.
<img width="110" alt="Screenshot 2023-06-22 at 8 09 17 PM" src="https://github.com/linux-china/jetbrains-just-plugin/assets/10589586/f46b4f9e-1ff6-4387-9cdb-2ebff81f2e47">

**Comment by linux-china** [comment]
In 0.6.1, 16x16 will be used as justfile icon
