### ISSUE TITLE
If/Else blocks without spaces surrounding commands aren't highlighted correctly

### ISSUE THREAD

**Issue by timlyo** [linux-china/jetbrains-just-plugin#12]
I've noticed that missing spaces around if/else blocks cause the rest of the file to not be parsed correctly. I've done some experimenting with the line that breaks it and found a minimal setup that replicates, as shown in the image.

![image](https://github.com/linux-china/jetbrains-just-plugin/assets/4664125/cc1e9170-8d88-4b11-ac1c-9308e590eb0a)

I'm on `PyCharm 2023.1.3` and using plugin version `0.3.6`.

Here's the above in text in case it helps to replicate

```just
thingy := if `true` { `ls` } else { "ls" }
thingy := if `true` {`ls` } else { "ls" }
thingy := if `true` { `ls` } else { "ls"}
thingy := if `true` {`ls`} else {"ls"}
# also not highlighted until next valid block
thingy := if `true` {`ls` } else { "ls" }
# Is highlighted
```

**Comment by linux-china** [comment]
@timlyo  it was caused by Flex during token analysis.  Now it's hard for me to fix this problem, and I should rewrite flex logic for this case.  Now you should add space, and sorry for this trouble.

```
thingy := if `true` { `ls` } else { "ls" }
thingy := if `true` { `ls` } else { "ls" }
thingy := if `true` { `ls` } else { "ls" }
thingy := if `true` { `ls` } else { "ls" }
# also not highlighted until next valid block
thingy := if `true` { `ls` } else { "ls" }
# Is highlighted
```

**Comment by linux-china** [comment]
Lex rewrite with version 0.5.2, please check it.

**Comment by timlyo** [comment]
Just updated, looks like it's fixed. Thankyou.

![image](https://github.com/user-attachments/assets/46b6ed5d-ec63-4985-9161-5eb6d366bfaa)
