### ISSUE TITLE
Import statement causes syntax error

### ISSUE THREAD

**Issue by wwidergoldbsc** [linux-china/jetbrains-just-plugin#19]
The following justfile contents are valid and work as expected, yet the plugin marks the import statement as an error and breaks the Plugin for the current file.

![image](https://github.com/linux-china/jetbrains-just-plugin/assets/100779487/a5783225-7ca5-43fe-8194-5a2b4162542d)

**Comment by linux-china** [comment]
Merged, and I will release 0.4.2 version ASAP.
