### ISSUE TITLE
Icon looks out of place

### ISSUE THREAD

**Issue by dhruvkb** [linux-china/jetbrains-just-plugin#2]
Thanks for the incredible plugin. I just wanted to point out that the icon for the Justfile (the black circle with 2 dots) looks out of place when compared with the other icons.

<img width="299" alt="Screenshot 2022-04-29 at 5 02 36 AM" src="https://user-images.githubusercontent.com/16580576/165870569-a2858248-82e3-45d9-ab47-137dcd38c237.png">

Can we use some icon from [JetBrains' default set of icons](https://jetbrains.design/intellij/resources/icons_list/)? They have a lot of good ones that can meaningfully convey a task runner file. In fact, the icon for a plain file `AllIcons.FileTypes.Any_type` with a superimposed green run icon `AllIcons.Nodes.RunnableMark` would look pretty decent.

**Comment by linux-china** [comment]
Yes,  icon in file explore tool window should be 12x12, and I corrected it already.

**Comment by dhruvkb** [comment]
The icon that you have chosen for Justfile (the circle with two vertically aligned dots) doesn't suit the IDE when using a dark theme. It's very difficult to see as it is, and nearly impossible when that file is selected.

<img width="339" alt="Screenshot 2022-06-09 at 4 10 28 AM" src="https://user-images.githubusercontent.com/16580576/172737791-b2f9ddc7-9428-46ab-ba8e-b9751b98f498.png">

**Comment by linux-china** [comment]
@dhruvkb  could you submit an issue on https://github.com/casey/just for icon art work?  :)   If not possible, and I will use run icon instead of current just icon in next version.
