### ISSUE TITLE
Support 2024.1

### ISSUE THREAD

**Issue by nandorholozsnyak** [linux-china/jetbrains-just-plugin#21]
IntelliJ's new EAP is live with the 2024.1 version.

Is it possible to support the new version? Can the plugin be built for newer versions like without an end version to overcome these small upgrades for newer versions if the plugin API does not change?

**Comment by nandorholozsnyak** [comment]
https://plugins.jetbrains.com/docs/intellij/build-number-ranges.html#build-number-validity

**Comment by linux-china** [comment]
0.4.1 released.
