### ISSUE TITLE
Update syntax to support recipe attribute confirm("prompt")

### ISSUE THREAD

**Issue by lokkju** [linux-china/jetbrains-just-plugin#26]
Justfile supports the recipe attribute `[confirm("prompt")]` since at least 1.23.0. Attempting to use this attribute shows as a language syntax error

Example:
```
[confirm("echo foo?")]
foo:
    echo "foo"
```

Result:
![Screenshot from 2024-04-22 11-05-58](https://github.com/linux-china/jetbrains-just-plugin/assets/235371/ff158153-8f94-405c-b6f7-0e6d1815a069)`

Reference: https://just.systems/man/en/chapter_32.html

**Comment by TTiger** [comment]
+1 having same issue

**Comment by nandorholozsnyak** [comment]
+1 here.
Group syntax is also not supported (yet). That would be helpful.
![image](https://github.com/linux-china/jetbrains-just-plugin/assets/11406183/6c34e1bb-e0a9-4388-848d-5b2e6c8e1372)

**Comment by linux-china** [comment]
Fixed on 0.5.1.
