### ISSUE TITLE
Parameter with default value leads to invalid syntax error from plugin.

### ISSUE THREAD

**Issue by motlin** [linux-china/jetbrains-just-plugin#27]
My recipe:

```justfile
# mvn verify
verify mvn="mvnd":
    {{mvn}} verify
```

The syntax error from the plugin: `'&', '&&', ';', '\n', '|', '|&' or '||' expected, got '}'`

<img width="596" alt="Screenshot 2024-05-21 at 11 24 57 AM" src="https://github.com/linux-china/jetbrains-just-plugin/assets/244258/a3f1c05e-f2ee-4902-bad2-9e58328c13e8">

**Comment by linux-china** [comment]
this is error of Bash because of language injection for recipe block.  Now it's hard to fix this problem.

**Comment by motlin** [comment]
@linux-china I understand, but wouldn't it be better not to inject a language there? It's bash plus just syntax. It may not even be bash if the justfile uses the directive `set shell := [...]`

**Comment by linux-china** [comment]
No worry, I added the logic to exclude language injection if code starts with `{{`  or `${`.   Fixed on version 0.5.2, and submitted to plugin marketplace for approval.

**Comment by motlin** [comment]
Thank you!

**Comment by linux-china** [comment]
Please check on version 0.5.2.

**Comment by motlin** [comment]
I'm getting a different error now and it's hard to tell if it's related to the changes or it was always there. This position in the file is after usages of the syntax described in this issue, so it does look like the fix worked.

![image](https://github.com/user-attachments/assets/b583cd18-680a-494d-9b4d-84f21fde8cb1)

**Comment by linux-china** [comment]
@motlin  yes. It's bug.  Fixed on version 0.5.3

**Comment by motlin** [comment]
I'm getting a different error now, right at the top of the file.

![image](https://github.com/user-attachments/assets/002af4fe-07e4-4adf-b1a7-7668f7930428)

**Comment by linux-china** [comment]
@motlin  It has been fixed, and please try 0.6.0 later.

**Comment by motlin** [comment]
Thanks @linux-china! If you'd like to test with [the justfile I'm using, it's the one in the Liftwizard project](https://github.com/liftwizard/liftwizard/blob/main/justfile).

The parser is getting past the previous errors, but now I see a syntax error very similar to the first one I reported. This time it's inside a shebang script.

<img width="707" alt="image" src="https://github.com/user-attachments/assets/85a0a7ed-2e75-4767-9a0c-56cac8ed5cce">

**Comment by linux-china** [comment]
@motlin  It's caused by inspection of  shell language injection.  I have disabled language injection for variables references.   

Please try version 0.6.1.  

![image](https://github.com/user-attachments/assets/6610b1fd-9af8-4c92-86bc-02f4950b4648)

**Comment by motlin** [comment]
LGTM, thank you!

**Comment by linux-china** [comment]
@motlin  a change for highlight: 

- Enable highlight for param in quotation mark style: `echo "{{name}"` or `echo '{{name}}'`

If param as command name, such as `{{mvn}} verify`, please use `exec '{{mnv}}' verify` instead if you want syntax highlight.
