### ISSUE TITLE
Missing syntax support

### ISSUE THREAD

**Issue by sja** [linux-china/jetbrains-just-plugin#3]
Example:
```
export VAR_A := "a b c"
export VAR_AB := VAR_A + " d e f"
```
The parser gives an error here between `VAR_A` and `+`:
```
JustToken.COMMENT, JustToken.KEYWORD_ALIAS, JustToken.KEYWORD_EXPORT, JustToken.KEYWORD_SET, JustToken.NEW_LINE, JustToken.RECIPE_NAME, JustToken.SHEBANG or JustToken.VARIABLE expected
```
I'm using 0.2.1 with GoLand 2022.1.

**Comment by nem75** [comment]
In the same vein: `… := if …` throws off the parser, as well as one-liner if-else constructs. See here:

<img width="504" alt="image" src="https://user-images.githubusercontent.com/1327785/167365397-ddcd5d5a-bc75-43d3-b18e-0d54ef66bf25.png">

For reproduction:

```
export TEST1 := if os() == 'x' { 'y' } else { 'z' }
export TEST2 := if os() == 'x' { `echo a` } else { `echo b` }
```

Sorry to say, but in the plugin's current state we're better off with the GNU Makefile file type.

**Comment by phillipross** [comment]
I bumped into this issue too w/ IDEA 2022.1.1

At first I thought it was an issue with just until I realized the file works but its the plugin that marks it as invalid 😅

**Comment by linux-china** [comment]
Yes, it's a bug, and fixed already.   I have uploaded a new version to JetBrains plugin marketplace, and it will be available in 1-2 days. 

![image](https://user-images.githubusercontent.com/46711/171303999-d7cea3e5-8923-4beb-ac27-b8a897caa535.png)
