### ISSUE TITLE
'export' and 'import' seem to be disallowed for a recipe name.

### ISSUE THREAD

**Issue by adamryczkowski** [linux-china/jetbrains-just-plugin#30]
I believe they are treated as some form of keywords:

![image](https://github.com/user-attachments/assets/070789ec-eff5-4a61-b149-e9cbfe8f3cd8)

I use up-to-date CLion on Ubuntu 22.04.

**Comment by linux-china** [comment]
:)  don't use key words as recipe name.  It's some hard to fix.

**Comment by linux-china** [comment]
@adamryczkowski    fixed on version 0.6.4, and it will be released ASAP.

![Snip20241015_4](https://github.com/user-attachments/assets/a6d32701-bc39-4a64-bdae-e2ebdbc56fe3)
