### ISSUE TITLE
`env_var_or_default` function second argument is not recognized

### ISSUE THREAD

**Issue by fabiomoratti** [linux-china/jetbrains-just-plugin#32]
The `env_var_or_default` function (see documentation [here](https://just.systems/man/en/functions.html?highlight=env_var_or_default#environment-variables)) is not recognized.

The following line:

```
aws_profile := env_var_or_default('JUST_ENV_AWS_PROFILE', default_aws_profile)
```

Triggers the error: 

_JustToken. COMMENT, JustToken. KEYWORD_ALIAS, JustToken. KEYWORD_EXPORT, JustToken. KEYWORD_IMPORT, JustToken. KEYWORD_MOD, JustToken. KEYWORD_SET, JustToken. NEW_LINE, JustToken. OPEN_BRACKET, JustToken. RECIPE_NAME, JustToken. SHEBANG or JustToken. VARIABLE expected, got 'default_aws_profile)'_

just after the comma for the second argument of the function.

Note that the same error is triggered for `env(key, default)`, an alias of` env_var_or_default`.

Thanks for the awesome plugin that makes writing just file much more easy.

**Comment by linux-china** [comment]
@fabiomoratti  Fixed with version 0.6.0, and please try later.
