### ISSUE TITLE
Activate Project Interpreter to execute recipe

### ISSUE THREAD

**Issue by linux-china** [linux-china/jetbrains-just-plugin#34]
For example: Python virtualenv, Java JDK etc.

**Comment by linux-china** [comment]
@funkyfuture  Fixed with version 0.6.3. If any problem, let me know.

**Comment by funkyfuture** [comment]
thanks, it works.

then there's *just* the issue left that the console output isn't colored, which is is sometimes useful when tools encode information by using colors, usually something to catch attention or to distinguish text contents.

**Comment by linux-china** [comment]
@funkyfuture   I disabled color output on Windows because of a bug  :)   I will have a test and fix color output on Windows.

**Comment by linux-china** [comment]
@funkyfuture  Fixed with version 0.6.6.

**Comment by funkyfuture** [comment]
i have only reasons to despise the Windows OS family. most times i use PyCharm on Ubuntu.

**Comment by funkyfuture** [comment]
sorry  for the emotions expressed: i wanted to point out that i'm not using Windows at all.

**Comment by linux-china** [comment]
@funkyfuture  I closed this issue. If still some problems, please create an new issue with screenshot. thanks.
