### ISSUE TITLE
Recipes with default arguments evaluated via function calls aren't parsed correctly

### ISSUE THREAD

**Issue by brykgroup-andrews** [linux-china/jetbrains-just-plugin#35]
Given a simple justfile such as:
```just
a b=f():
    echo 'hi'
```
an error is flagged up - `JustToken. RECIPE_PARAM_NAME expected, got 'b'` - and parsing/highlighting breaks.

To make matters worse, if you give it a non-empty string argument, such as
```just
a b=f('a'):
    echo 'hi'
```
parsing breaks.

Interestingly, if you then put `''` somewhere in the body, it closes the string. Not totally clear why. For example:
```just
a b=f('a'):
    echo ''
```
causes the rest of the file to parse itself correctly until something like the second example is encountered again.

**Comment by linux-china** [comment]
Fixed with version 0.6.6, and it will be released ASAP.

![image](https://github.com/user-attachments/assets/2e9818b3-5a26-4238-a548-8ede635c55ca)
