### ISSUE TITLE
Allow expanding macros in run configs recipe args

### ISSUE THREAD

**Issue by stijndcl** [linux-china/jetbrains-just-plugin#39]
Would be nice to be able to use [the built-in macros](https://www.jetbrains.com/help/idea/built-in-macros.html
) in the recipe args for a run config. `$Prompt$` in particular is very handy, as it allows you to type in recipe args and even set default values.

Plugin SDK docs: https://plugins.jetbrains.com/docs/intellij/run-configurations.html#expanding-macros-before-execution 

Desired workflow:
- Create a run config, add `$Prompt:name:default$` to the recipe args
- When executing the run config, the IDE should show a pop-up to ask for a value

**Comment by linux-china** [comment]
@stijndcl  Fixed with version 0.6.8.
