### ISSUE TITLE
执行报错了，怎么提前执行 conda activtate pythonenv 呢?

### ISSUE THREAD

**Issue by mokeyish** [linux-china/jetbrains-just-plugin#4]
我在 pycharm 上写了这么一个脚本，安装 python 开发依赖的，但是 python 需要提前激活虚拟环境，否则点击绿色按钮全都报错了。

![image](https://user-images.githubusercontent.com/16131917/172173743-20966757-d07f-4c9a-b3ea-145c83bf1cfb.png)

直接再命令行上执行 `just dev` 是可以的。但这绿色小按钮似乎成了鸡肋，全部执行报错。

类似的开发环境管理有：`conda`、`pip`、`nvm`、`sdk` 等等。

**我是 windows 上的使用的。**

**Comment by linux-china** [comment]
如果你通过点击程序运行PyCharm，PyCharm是不知道当前的terminal对应的环境信息的。 PyCharm支持从命令行启动，这样就可以继承当前环境的所有信息，你使用进入项目目录后，然后通过`pycharm .` 这种方式试试。 注意： 不能有其他Pycharm实例已经运行啦，不然会从已经运行的PyCharm实例那边获取环境信息。 

这种环境切换的问题，最好介入一下PATH变量，如针对Node.js的场景，just给出的方案如下，官方README有说明。 

```
export PATH := "./node_modules/.bin:" + env_var('PATH')
```

这个问题一直都是有的，如不在项目目录下，你执行 `just --justfile  d:\app1\justfile abc` 同样也没法给你激活项目的环境要求的，最好能够在justfile中指定一下环境变量信息，这样在任何目录和环境下都可以运行justfile中的recipe。
