### ISSUE TITLE
Parse error for recipes with blank lines

### ISSUE THREAD

**Issue by nem75** [linux-china/jetbrains-just-plugin#5]
When using the plugin, blank lines in recipes are marked as an error although just accepts them quite fine.

justfile to reproduce:

```
with-blank-line:
	echo this

	echo that

without-blank-line:
	echo this
	echo that
```

Both recipes execute, but the plugin marks the first `echo that` line with an error.

**Comment by linux-china** [comment]
Yes, I know this problem, and it's some challenge because of token parsing rules.  Now please remove empty line in recipe script body, and I will try to fix this problem.  :)

**Comment by linux-china** [comment]
@nem75  fixed https://github.com/linux-china/jetbrains-just-plugin/commit/e3fa5098d73b90f7d6c3090444e0e6df9f882c5a I will release a new version soon. 


![image](https://user-images.githubusercontent.com/46711/174388463-59c0b459-f2a4-4a41-82ed-ebc51d16b0f5.png)
