### ISSUE TITLE
Feature request: syntax highlighting / inspection for inline shell scripts

### ISSUE THREAD

**Issue by nem75** [linux-china/jetbrains-just-plugin#6]
The Jetbrains Makefile plugin uses the "Shell script" language syntax highlighting and inspections for inline shell scripts in recipes.

Would be neat if this plugin could do the same.

Unfortunately I have no clue about programming Jetbrains plugins, but some relevant piece of code in the Makefile plugin seems to be this:

https://github.com/JetBrains/intellij-plugins/blob/0f07ca63355d5530b441ca566c98f17c560e77f8/makefile/src/com/jetbrains/lang/makefile/MakefileShellLanguageInjector.kt#L11

**Comment by nem75** [comment]
Rendered with Makefile plugin:

![image](https://user-images.githubusercontent.com/1327785/172383581-f662a03d-3b0a-4c3c-80fe-8ec23da59ffe.png)

Rendered with just-plugin:

![image](https://user-images.githubusercontent.com/1327785/172383884-7923fb7d-b21a-4b07-a738-be10f5c627de.png)

**Comment by linux-china** [comment]
Yes, it's a required feature.  I have implemented it https://github.com/linux-china/jetbrains-just-plugin/blob/master/src/test/kotlin/org/jetbrains/plugins/template/JustCodeBlockLanguageInjector.kt   and I should do more testing, for example recipes with python.  I will enable it on next version, and it's a trial feature.

**Comment by nem75** [comment]
Ooh, shiny. Should've checked the branches I guess. Thanks in advance! :)

**Comment by linux-china** [comment]
@nem75  done with version 0.2.4

**Comment by nem75** [comment]
Hey @linux-china, thanks a lot.

Just noticed though, syntax highlighting only seems to work for implicit shell scripts. As soon es I define a script explicitly via shebang, the highlighting is gone. :/

Any chance this could be fixed?

![image](https://user-images.githubusercontent.com/1327785/174613452-fcd08a49-2308-4b35-b5c9-e133216a5a2d.png)

**Comment by linux-china** [comment]
@nem75  :)  my fault, and you should use `#!/usr/bin/env sh`  now. I will add bash, zsh, fish and nu support :)

**Comment by nem75** [comment]
Can't, we use bash syntax by default. But I'm happy to wait. :)
