### ISSUE TITLE
[Feature Request] - Popup menu for executing Just recipes

### ISSUE THREAD

**Issue by nandorholozsnyak** [linux-china/jetbrains-just-plugin#7]
With the [Maven Helper](https://plugins.jetbrains.com/plugin/7179-maven-helper) plugin the IDEA is getting a cool feature, by pressing down the Ctrl+Alt+Shift+R (a bit long shortcut) a popup will appear with the available goals and if there is any Run configurations for the Root module it will be also shown.

Here is a picture:
![image](https://user-images.githubusercontent.com/11406183/199009951-2cc0dd28-ee03-423e-9081-85ff78fcf132.png)

Is there any way to have this noice feature in the Just plugin as well? I have a few bookmarks for my Just recipes to jump there but it would be nice to have a "quicker" way to execute those recipes.

**Comment by linux-china** [comment]
Fixed in version 0.3.1. 

- Popup menu for executing Just recipes: `Run Menu -> Run Just Recipe on Root Module` or `ctrl shift alt J`

**Comment by nandorholozsnyak** [comment]
Thank you, I'm super curious about the feature :)

**Comment by nandorholozsnyak** [comment]
Thank you for the feature, I'm curious if the name of the recipe (that is above the recipe with the hashtag (#)) could be included somehow to have a description for it or not? 

Thank you!!

**Comment by linux-china** [comment]
@nandorholozsnyak  you reminded me, and I will take a look and adjust the menu popup with `just -l`

**Comment by nandorholozsnyak** [comment]
Thank you.

**Comment by nandorholozsnyak** [comment]
"Just" got the update, looking so cool, thank you!
