### ISSUE TITLE
Only 80 columns used on Windows

### ISSUE THREAD

**Issue by knutwannheden** [linux-china/jetbrains-just-plugin#8]
When I run a recipe from within the editor, the output only uses 80 columns. I am not sure what the issue is, but I suspect it has to do with how the plugin launches the command. See screenshot.

![image](https://user-images.githubusercontent.com/408765/199188985-c6e4eee5-fb5d-410d-a48c-87d92bb84789.png)

**Comment by linux-china** [comment]
@knutwannheden  some weird, and it works well with IntelliJ IDEA `Build #IU-223.7126.7`.  Maybe it's a bug of IntelliJ IDEA, and what's your IntelliJ version?
